### PR TITLE
Recycle view

### PR DESCRIPTION
**Pull request by mikemorris**
Refs #142

### CODE REVIEW

**Comment by mikemorris** [comment]
Any idea why I'm hitting [`"Error: Request has already been responded to, or was canceled."`](https://github.com/mapbox/node-mapbox-gl-native/blob/ba09ea9ef9c53bc6759abac66e84ce9115cb4c5c/src/node_request.cpp#L61) when compiling this branch against https://github.com/mapbox/mapbox-gl-native/pull/1964 @tmpsantos?

**Comment by mikemorris** [comment]
Hrm, looks like this error was introduced by https://github.com/mapbox/mapbox-gl-native/commit/07086981fe18aebb04eb55c24286b06eb2bf4c6f#diff-ba5f71fcdf1810036d329e49ea750ce0 @tmpsantos, I'm hitting it compiling master against `v0.4.1`

**Comment by mikemorris** [comment]
Looks like running `test/js/concurrency.test.js` triggers this instantly, while it will eventually hit it running `test/render.test.js` so I think the commit linked above is causing this issue.

**Comment by mikemorris** [comment]
Other errors:
```
error: no viable conversion from 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >' to '_Atomic(std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >)'
```
Only on [Travis compiling on OS X](https://travis-ci.org/mapbox/node-mapbox-gl-native/jobs/73610114), I have no idea what's going on here.

**Comment by tmpsantos** [comment]
> Hrm, looks like this error was introduced by mapbox/mapbox-gl-native@0708698#diff-ba5f71fcdf1810036d329e49ea750ce0

Hmm this is weird because this patch should be a no-op, removing only dead code.

**Comment by tmpsantos** [comment]
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  OpenGL context was already current
> Sometimes tests throw this error instead of the req.respond error, I'm pretty sure this is stemming from calling view->activate() in MapContext::setView instead of in the constructor.

I think the problem is because when you replace the new View on the `MapContext::setView` you don't call `view->deactivate()` (this will ultimately unbind the GL context from a particular thread) .

`view->deactivate()` must be called from the Map thread (i.e. from the `MapContext`). I will comment on your PR implementing the `Map::setView` some ideas.

**Comment by mikemorris** [comment]
Yep, that was it for `OpenGL context was already current`, only hitting the `req.respond` error now @tmpsantos. Per chat with @jfirebaugh we're gonna hold off on the `setView` functionality though, so this is gonna be a lower priority fix now.

**Comment by mikemorris** [comment]
Ugh, seeing `Request has already been responded to, or was canceled.` in the much simpler [headless-resize](https://github.com/mapbox/node-mapbox-gl-native/tree/headless-resize) branch too, thoughts @tmpsantos?

**Comment by mikemorris** [comment]
-> #147

**Comment by mikemorris** [comment]
Oh weird, `OpenGL context was already current` was coming from the garbage collector trying to destroy a `NodeView` containing a still-active `HeadlessView`, and trying to call [`activate()`](https://github.com/mapbox/mapbox-gl-native/blob/76c937f119bdc673fef2675a4db22731cde85dfe/platform/default/headless_view.cpp#L211) in the `HeadlessView` destructor.

**Comment by mikemorris** [comment]
-> #149

**Pull request closed without merging**
