### PR TITLE
Map destruction hanging with pending requests

### PR DESCRIPTION
**Pull request by tmpsantos**
[Test that returns an error on failed vector tile requests](https://github.com/mapbox/node-mapbox-gl-native/blob/e4536789eb1980bd7fa2d1eaba4fd7ccef4d34c5/test/js/map.test.js#L201-L210) in `test/js/map.test.js` is currently skipped pending resolution of https://github.com/mapbox/mapbox-gl-native/pull/1657

### CODE REVIEW

**Comment by tmpsantos** [comment]
@mikemorris please review. More details on the commits changelogs.

**Comment by mikemorris** [comment]
Interesting catch on the broken move semantics on `v8::UniquePersistent`, that explains why I couldn't get it to compile. I'm thinking about implementing `v8::StdPersistentValueMap` from [v8-util.h](https://code.google.com/p/v8/source/browse/trunk/include/v8-util.h) as an alternative solution to [persistent handles are no longer copyable by default](https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/), up to you which approach would be better.

**Comment by tmpsantos** [comment]
@mikemorris is saw the `v8::StdPersistentValueMap` too, but I liked more the idea of keeping the code path of the old and the new versions of node as close as possible. Also, when we get access to `v8::UniquePersistant` on a `std::map`, the migration would be more straightforward, because we won't need to change the container type.

**Comment by mikemorris** [comment]
:rocket: Merge it!

**Pull request merged**
