### PR TITLE
Removed unused method on NodeFileSource

### PR DESCRIPTION
**Pull request by tmpsantos**

### CODE REVIEW

**Comment by mikemorris** [comment]
This was designed to mirror the virtual methods in `mbgl::FileSource`, is this not necessary or just no longer needed?

**Comment by tmpsantos** [comment]
> This was designed to mirror the virtual methods in mbgl::FileSource, is this not necessary or just no longer needed?

This was removed from the base class `mbgl::FileSource`.

**Comment by jfirebaugh** [comment]
:+1:

**Comment by mikemorris** [comment]
:+1: Good to merge.

**Pull request merged**
